export const dummyCampaigns = [
  {
    id: 1,
    title: "Flood Relief Assam",
    category: "Disaster Relief",
    targetAmount: 5000000,
    collectedAmount: 3500000,
    status: "Active",
    isVerified: true,
    image: "https://images.unsplash.com/photo-1542125387-c71274d94f0a?auto=format&fit=crop&q=80&w=800",
    description: "Provide emergency flood relief, clean water, and food to affected families in Assam.",
    donorsCount: 450,
  },
  {
    id: 2,
    title: "Cancer Treatment Support",
    category: "Medical",
    targetAmount: 1200000,
    collectedAmount: 850000,
    status: "Active",
    isVerified: true,
    image: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&q=80&w=800",
    description: "Help Rajesh, a 12-year old boy, afford his life-saving leukemia treatments.",
    donorsCount: 120,
  },
  {
    id: 3,
    title: "Education for Rural Children",
    category: "Education",
    targetAmount: 800000,
    collectedAmount: 400000,
    status: "Active",
    isVerified: false,
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=800",
    description: "Building a new primary school and providing supplies for children in rural villages.",
    donorsCount: 85,
  },
  {
    id: 4,
    title: "Food Drive for Homeless",
    category: "Food & Hunger",
    targetAmount: 500000,
    collectedAmount: 500000,
    status: "Completed",
    isVerified: true,
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=800",
    description: "Distributing daily meals to over 1000 homeless individuals across the city.",
    donorsCount: 200,
  },
  {
    id: 5,
    title: "Disaster Recovery Fund",
    category: "Disaster Relief",
    targetAmount: 2000000,
    collectedAmount: 150000,
    status: "Active",
    isVerified: true,
    image: "https://images.unsplash.com/photo-1582216443425-4c0feee277ff?auto=format&fit=crop&q=80&w=800",
    description: "Rebuilding homes destroyed in recent earthquakes and providing temporary shelters.",
    donorsCount: 30,
  }
];

export const platformStats = {
  totalFundsRaised: 25000000,
  activeCampaigns: 42,
  beneficiariesHelped: 12500,
  verifiedReports: 180,
};
